import express from 'express';import multer from 'multer';import Product from '../models/Product.js';import {auth,role} from '../middleware/auth.js';
const r=express.Router();const upload=multer({storage:multer.diskStorage({destination:'uploads/',filename:(q,f,cb)=>cb(null,Date.now()+'-'+f.originalname)}),limits:{fileSize:2*1024*1024}});
const valid=p=>p.name&&Number.isInteger(+p.priceCents)&&+p.priceCents>0&&Number.isInteger(+p.stock)&&+p.stock>=0;
r.get('/',async(req,res,next)=>{try{const q=req.query.q?{$or:[{name:{$regex:req.query.q,$options:'i'}},{category:{$regex:req.query.q,$options:'i'}}]}:{};res.json(await Product.find(q).populate('sellerId','name').sort('-createdAt'))}catch(e){next(e)}});
r.get('/mine',auth,role('seller'),async(req,res,next)=>{try{res.json(await Product.find({sellerId:req.user._id}).sort('-createdAt'))}catch(e){next(e)}});
r.get('/:id',async(req,res,next)=>{try{const p=await Product.findById(req.params.id).populate('sellerId','name');if(!p)return res.status(404).json({message:'Product not found'});res.json(p)}catch(e){next(e)}});
r.post('/',auth,role('seller'),upload.single('image'),async(req,res,next)=>{try{if(!valid(req.body))return res.status(400).json({message:'Provide a name, price in cents, and non-negative stock'});res.status(201).json(await Product.create({...req.body,sellerId:req.user._id,image:req.file?'/uploads/'+req.file.filename:''}))}catch(e){next(e)}});
r.put('/:id',auth,role('seller'),upload.single('image'),async(req,res,next)=>{try{const p=await Product.findOne({_id:req.params.id,sellerId:req.user._id});if(!p)return res.status(404).json({message:'Product not found'});if(!valid(req.body))return res.status(400).json({message:'Invalid product values'});Object.assign(p,req.body);if(req.file)p.image='/uploads/'+req.file.filename;await p.save();res.json(p)}catch(e){next(e)}});
r.delete('/:id',auth,role('seller'),async(req,res,next)=>{try{const p=await Product.findOneAndDelete({_id:req.params.id,sellerId:req.user._id});if(!p)return res.status(404).json({message:'Product not found'});res.status(204).end()}catch(e){next(e)}});export default r;
